### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by lucassprogramer** [tawfiqkhalilieh/chessCheater#3]
![image](https://user-images.githubusercontent.com/129118824/228075279-6316782e-02c4-46fd-88cc-9a28ff37c2fb.png)

**Comment by lucassprogramer** [comment]
what do i do?

**Comment by lucassprogramer** [comment]
![image](https://user-images.githubusercontent.com/129118824/228075944-d7fefa1a-de4b-4d44-9c0e-135f63b44914.png)

**Comment by tawfiqkhalilieh** [comment]
make sure you have chrome browser on your pc and installed the selenium chrome driver

**Comment by tawfiqkhalilieh** [comment]
follow these steps

![image](https://user-images.githubusercontent.com/87164562/228777437-876529fa-e2b8-4fc5-9011-7a9902d69ca3.png)
